"""initial migration

Revision ID: 92e191f3e728
Revises: 
Create Date: 2018-02-12 14:31:13.633841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92e191f3e728'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('firstname', sa.String(length=255), nullable=True),
    sa.Column('lastname', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_firstname'), 'employees', ['firstname'], unique=False)
    op.create_index(op.f('ix_employees_lastname'), 'employees', ['lastname'], unique=False)
    op.create_index(op.f('ix_employees_username'), 'employees', ['username'], unique=False)
    op.create_table('employers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('firstname', sa.String(length=255), nullable=True),
    sa.Column('lastname', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employers_email'), 'employers', ['email'], unique=True)
    op.create_index(op.f('ix_employers_firstname'), 'employers', ['firstname'], unique=False)
    op.create_index(op.f('ix_employers_lastname'), 'employers', ['lastname'], unique=False)
    op.create_index(op.f('ix_employers_username'), 'employers', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employers_username'), table_name='employers')
    op.drop_index(op.f('ix_employers_lastname'), table_name='employers')
    op.drop_index(op.f('ix_employers_firstname'), table_name='employers')
    op.drop_index(op.f('ix_employers_email'), table_name='employers')
    op.drop_table('employers')
    op.drop_index(op.f('ix_employees_username'), table_name='employees')
    op.drop_index(op.f('ix_employees_lastname'), table_name='employees')
    op.drop_index(op.f('ix_employees_firstname'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
